// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hero-redesign/EleganteOscuro.tsx": () => import("../components/mockups/hero-redesign/EleganteOscuro.tsx"),
  "./components/mockups/hero-redesign/ModernoLimpio.tsx": () => import("../components/mockups/hero-redesign/ModernoLimpio.tsx"),
  "./components/mockups/hero-redesign/VibranteGradiente.tsx": () => import("../components/mockups/hero-redesign/VibranteGradiente.tsx")
};
